MARKET_SIGNALS = {
    "fintech": [
        ("🟠", "Hacker News", "2h ago", "How we closed first 10 payments ops buyers without a sales team"),
        ("🔴", "Reddit r/fintech", "3h ago", "Cold outbound not converting in Payments — what changed in 2025?"),
        ("🟠", "Hacker News", "6h ago", "Founder-led sales in Payments — what actually works at $1M ARR"),
        ("🟢", "TechCrunch", "4h ago", "Fintech B2B sales cycles stretched 40% — compliance now the gate"),
        ("🔵", "Crunchbase", "today", "14 Payments SaaS Series A closes in May 2026"),
        ("🔴", "Reddit r/startups", "yesterday", "AE hired 3 months ago, zero closes — what did I miss?"),
        ("🟠", "Hacker News", "8h ago", "Why outbound fails in regulated Fintech markets"),
        ("🔴", "Reddit r/fintech", "5h ago", "Core banking switch — 18 month sales cycle reality"),
    ],
    "healthtech": [
        ("🟠", "Hacker News", "3h ago", "Selling to hospital procurement — what nobody tells you"),
        ("🔴", "Reddit r/healthtech", "5h ago", "HIPAA compliance adding 60 days to our sales cycle"),
        ("🟢", "TechCrunch", "today", "Digital health Series A funding up 35% YoY in 2026"),
        ("🔵", "Crunchbase", "today", "12 Healthtech B2B Series A closes this month"),
        ("🟠", "Hacker News", "yesterday", "EHR integration the #1 sales objection in health SaaS"),
        ("🔴", "Reddit r/startups", "2h ago", "Clinical buyer vs IT buyer — who actually signs the contract?"),
        ("🟢", "TechCrunch", "6h ago", "CMS reimbursement changes opening new Healthtech buying window"),
        ("🔵", "Crunchbase", "yesterday", "Digital therapeutics funding rebounds after 2024 slowdown"),
    ],
    "legal_tech": [
        ("🟠", "Hacker News", "4h ago", "Selling legal SaaS — why lawyers are the worst champions"),
        ("🔴", "Reddit r/legaltech", "2h ago", "GC sign-off adding 90 days to every enterprise deal"),
        ("🟢", "TechCrunch", "today", "LegalTech investment hits $2.1B in Q1 2026"),
        ("🔵", "Crunchbase", "today", "8 LegalTech Series A closes — AI contract review dominates"),
        ("🟠", "Hacker News", "yesterday", "How to sell to law firms — the buying committee you never see"),
        ("🔴", "Reddit r/startups", "5h ago", "Legal SaaS ACV question — $30K or $80K for mid-market firms?"),
        ("🟢", "TechCrunch", "8h ago", "BigLaw AI adoption accelerating — 60% piloting tools in 2026"),
        ("🔴", "Reddit r/legaltech", "3h ago", "Bar association compliance blocking our enterprise deals"),
    ],
    "hr_tech": [
        ("🟠", "Hacker News", "2h ago", "CHRO buying cycle is 6 months — here is how to compress it"),
        ("🔴", "Reddit r/hrtech", "4h ago", "HR SaaS market saturated — how do you differentiate now?"),
        ("🟢", "TechCrunch", "today", "HR tech consolidation wave — 3 more acquisitions this month"),
        ("🔵", "Crunchbase", "today", "11 HRTech Series A closes — workforce analytics leads"),
        ("🟠", "Hacker News", "yesterday", "Selling to HR vs CFO — who actually controls the budget?"),
        ("🔴", "Reddit r/startups", "6h ago", "ATS replacement cycle — why 2026 is the window"),
        ("🟢", "TechCrunch", "3h ago", "AI hiring tools facing backlash — bias audits now mandatory"),
        ("🔴", "Reddit r/hrtech", "2h ago", "Return to office data — buyers want this benchmark now"),
    ],
    "edtech": [
        ("🟠", "Hacker News", "3h ago", "B2B EdTech sales — selling to procurement vs selling to teachers"),
        ("🔴", "Reddit r/edtech", "5h ago", "School district budget cycles — when to start outbound"),
        ("🟢", "TechCrunch", "today", "Enterprise L&D spend up 28% — workforce upskilling drives it"),
        ("🔵", "Crunchbase", "today", "9 EdTech Series A closes — corporate training dominates"),
        ("🟠", "Hacker News", "yesterday", "University procurement is broken — how we closed 3 deals anyway"),
        ("🔴", "Reddit r/startups", "4h ago", "EdTech ACV ceiling — why $15K is hard to break in K12"),
        ("🟢", "TechCrunch", "6h ago", "AI tutoring tools displacing legacy LMS in enterprise"),
        ("🔴", "Reddit r/edtech", "2h ago", "Title IV compliance killing our higher ed sales velocity"),
    ],
    "cybersecurity": [
        ("🟠", "Hacker News", "1h ago", "CISO budget cycles — Q4 is the only quarter that matters"),
        ("🔴", "Reddit r/netsec", "3h ago", "SOC2 as a sales tool — does it actually accelerate deals?"),
        ("🟢", "TechCrunch", "today", "Cybersecurity VC investment hits $18B in 2026 — AI sec leads"),
        ("🔵", "Crunchbase", "today", "16 Cybersecurity Series A closes — identity and access top"),
        ("🟠", "Hacker News", "yesterday", "Selling security to SMB — why fear is not a GTM strategy"),
        ("🔴", "Reddit r/startups", "4h ago", "Security procurement — IT says yes legal says no deal dies"),
        ("🟢", "TechCrunch", "5h ago", "NIS2 directive creating urgent buying window in Europe"),
        ("🔴", "Reddit r/netsec", "2h ago", "MSSP channel vs direct — which motion works at $2M ARR?"),
    ],
    "proptech": [
        ("🟠", "Hacker News", "4h ago", "Selling to real estate — why brokers are blockers not buyers"),
        ("🔴", "Reddit r/proptech", "2h ago", "PropTech sales cycle hit 9 months — interest rates killed urgency"),
        ("🟢", "TechCrunch", "today", "PropTech funding recovering — $3.2B raised in Q1 2026"),
        ("🔵", "Crunchbase", "today", "7 PropTech Series A closes — property management software leads"),
        ("🟠", "Hacker News", "yesterday", "How we closed 5 enterprise REITs in 6 months"),
        ("🔴", "Reddit r/startups", "6h ago", "CRE tech buyers — CFO or COO? Depends on deal size"),
        ("🟢", "TechCrunch", "8h ago", "AI property valuation tools attracting institutional interest"),
        ("🔴", "Reddit r/proptech", "3h ago", "Multifamily vs commercial — totally different GTM motions"),
    ],
    "insurtech": [
        ("🟠", "Hacker News", "3h ago", "Selling to insurance carriers — actuarial sign-off is the gate"),
        ("🔴", "Reddit r/insurtech", "5h ago", "InsurTech B2B sales cycle is 12 months minimum — plan for it"),
        ("🟢", "TechCrunch", "today", "InsurTech Series A activity up 40% — embedded insurance leads"),
        ("🔵", "Crunchbase", "today", "6 InsurTech raises this month — MGA platform tools dominate"),
        ("🟠", "Hacker News", "yesterday", "Why insurance buyers need 3 pilots before they sign anything"),
        ("🔴", "Reddit r/startups", "4h ago", "State regulation making InsurTech GTM a nightmare"),
        ("🟢", "TechCrunch", "6h ago", "AI underwriting tools cutting carrier loss ratios — buyers moving"),
        ("🔴", "Reddit r/insurtech", "2h ago", "Broker channel vs direct carrier — which pays more at scale?"),
    ],
    "supply_chain": [
        ("🟠", "Hacker News", "2h ago", "Supply chain SaaS — why the VP Ops is not the buyer"),
        ("🔴", "Reddit r/supplychaintech", "4h ago", "ERP integration blocking every enterprise deal we have"),
        ("🟢", "TechCrunch", "today", "Supply chain tech investment up 32% post-2025 disruption wave"),
        ("🔵", "Crunchbase", "today", "10 Supply Chain Series A closes — visibility tools lead"),
        ("🟠", "Hacker News", "yesterday", "How we sold to 3 Fortune 500 procurement teams in 8 months"),
        ("🔴", "Reddit r/startups", "5h ago", "Manufacturing SaaS ACV — why $50K is the floor not ceiling"),
        ("🟢", "TechCrunch", "7h ago", "Nearshoring trend creating new supply chain buying wave"),
        ("🔴", "Reddit r/supplychaintech", "3h ago", "SAP dependency — biggest objection in enterprise supply chain"),
    ],
    "marketing_tech": [
        ("🟠", "Hacker News", "2h ago", "MarTech is dead — what actually works for B2B growth in 2026"),
        ("🔴", "Reddit r/marketing", "3h ago", "CMO budget cuts hitting MarTech stack first — how to survive"),
        ("🟢", "TechCrunch", "today", "AI marketing tools consolidating — 3 major acquisitions this month"),
        ("🔵", "Crunchbase", "today", "13 MarTech Series A closes — revenue attribution tools lead"),
        ("🟠", "Hacker News", "yesterday", "Selling to CMO vs VP Demand Gen — totally different conversations"),
        ("🔴", "Reddit r/startups", "4h ago", "MarTech ACV dropped 20% — buyers want outcome pricing now"),
        ("🟢", "TechCrunch", "6h ago", "Third-party cookie death hitting MarTech buyers — urgency up"),
        ("🔴", "Reddit r/marketing", "2h ago", "ABM platform fatigue — buyers consolidating to 2 tools max"),
    ],
    "devtools": [
        ("🟠", "Hacker News", "1h ago", "Bottom-up PLG is dead for devtools — here is what replaced it"),
        ("🔴", "Reddit r/devops", "3h ago", "Developer tool fatigue — how many tools are in your stack?"),
        ("🟢", "TechCrunch", "today", "DevTools funding hits $4.1B — AI code generation leads"),
        ("🔵", "Crunchbase", "today", "18 DevTools Series A closes this month — observability surges"),
        ("🟠", "Hacker News", "yesterday", "Selling devtools to enterprise — PLG to sales-led in 6 steps"),
        ("🔴", "Reddit r/startups", "4h ago", "DevTool ACV expansion — how to go from $5K to $50K per account"),
        ("🟢", "TechCrunch", "5h ago", "GitHub Copilot adoption creating adjacent tool buying patterns"),
        ("🔴", "Reddit r/devops", "2h ago", "Platform engineering trend killing point solution devtools"),
    ],
    "climate_tech": [
        ("🟠", "Hacker News", "4h ago", "Carbon accounting SaaS — CFO or CSO? Who owns the budget?"),
        ("🔴", "Reddit r/climatetech", "2h ago", "ESG mandates creating forced buying — how to capture it"),
        ("🟢", "TechCrunch", "today", "Climate tech VC hits $12B in Q1 2026 — software layer surges"),
        ("🔵", "Crunchbase", "today", "9 ClimateTech Series A closes — scope 3 emissions tools lead"),
        ("🟠", "Hacker News", "yesterday", "CSRD compliance deadline creating 6 month buying window in EU"),
        ("🔴", "Reddit r/startups", "5h ago", "Sustainability SaaS — compliance beats mission in sales calls"),
        ("🟢", "TechCrunch", "7h ago", "SEC climate disclosure rules finalized — US enterprise buyers moving"),
        ("🔴", "Reddit r/climatetech", "3h ago", "Voluntary vs mandatory carbon markets — totally different buyers"),
    ],
    "logistics_tech": [
        ("🟠", "Hacker News", "3h ago", "Selling to 3PLs — ops director is champion CFO is the buyer"),
        ("🔴", "Reddit r/logistics", "5h ago", "Freight tech sales cycle — why Q1 and Q3 are dead zones"),
        ("🟢", "TechCrunch", "today", "Logistics tech Series A recovering — $2.8B raised YTD"),
        ("🔵", "Crunchbase", "today", "8 LogTech Series A closes — last mile optimization leads"),
        ("🟠", "Hacker News", "yesterday", "How we sold TMS software to 5 regional carriers in 4 months"),
        ("🔴", "Reddit r/startups", "4h ago", "Carrier tech ACV — why $40K is the sweet spot for mid-market"),
        ("🟢", "TechCrunch", "6h ago", "Autonomous delivery pilots creating new software buying cycle"),
        ("🔴", "Reddit r/logistics", "2h ago", "Shipper vs carrier GTM — two completely different sales motions"),
    ],
    "sales_tech": [
        ("🟠", "Hacker News", "2h ago", "Sales tech consolidation — buyers cutting stack from 12 to 4 tools"),
        ("🔴", "Reddit r/sales", "3h ago", "CRO budget cuts hitting sales tools first — what survived?"),
        ("🟢", "TechCrunch", "today", "AI SDR tools face backlash — reply rates hit all time low"),
        ("🔵", "Crunchbase", "today", "11 SalesTech Series A closes — revenue intelligence leads"),
        ("🟠", "Hacker News", "yesterday", "Selling sales tools to sales people — the hardest GTM motion"),
        ("🔴", "Reddit r/startups", "4h ago", "Sales tech ACV compression — buyers want usage pricing now"),
        ("🟢", "TechCrunch", "5h ago", "Gong and Clari moving upmarket — creating SMB gap for new entrants"),
        ("🔴", "Reddit r/sales", "2h ago", "Outbound sequence tools commoditized — where is the next wedge?"),
    ],
    "general": [
        ("🟠", "Hacker News", "2h ago", "B2B SaaS founders on the wrong first GTM hire"),
        ("🔴", "Reddit r/startups", "4h ago", "Founder-led sales breaking at $1M ARR — what actually changed"),
        ("🟢", "TechCrunch", "today", "Series A GTM motion — what top quartile looks like in 2026"),
        ("🔵", "Crunchbase", "today", "B2B SaaS Series A closes up 28% this month"),
        ("🟠", "Hacker News", "yesterday", "ICP clarity before your first AE hire — how to get there"),
        ("🔴", "Reddit r/SaaS", "3h ago", "Pipeline not converting — is it motion or ICP problem?"),
        ("🟢", "TechCrunch", "6h ago", "CAC payback stretching to 18 months — what top founders do"),
        ("🔴", "Reddit r/startups", "5h ago", "Mis-sequenced GTM hiring cost us $400K — what to do instead"),
    ],
    "b2b": [
        ("🟠", "Hacker News", "2h ago", "B2B sales motion in 2026 — what separates top quartile from the rest"),
        ("🔴", "Reddit r/b2bsales", "3h ago", "Outbound reply rates hit 2% — is cold email finally dead?"),
        ("🟠", "Hacker News", "5h ago", "How we built a repeatable B2B motion from founder-led in 6 months"),
        ("🟢", "TechCrunch", "today", "B2B SaaS multiples recovering — Rule of 40 back as the benchmark"),
        ("🔵", "Crunchbase", "today", "22 B2B SaaS Series A closes in May 2026 — vertical software leads"),
        ("🔴", "Reddit r/startups", "4h ago", "Champion vs economic buyer — closing the wrong person killed 3 deals"),
        ("🟠", "Hacker News", "yesterday", "B2B buying committees grew from 3 to 7 people — new playbook needed"),
        ("🔴", "Reddit r/sales", "2h ago", "Proof of concept requests up 60% — buyers derisk everything now"),
    ],
    "software": [
        ("🟠", "Hacker News", "1h ago", "Enterprise software sales — why the demo is killing your deal"),
        ("🔴", "Reddit r/software", "3h ago", "SaaS pricing models shifting — usage-based beating seat licenses"),
        ("🟠", "Hacker News", "4h ago", "Software consolidation wave — buyers cutting from 15 tools to 6"),
        ("🟢", "TechCrunch", "today", "Vertical software valuations up 40% — horizontal plays under pressure"),
        ("🔵", "Crunchbase", "today", "19 software Series A closes this month — workflow tools dominate"),
        ("🔴", "Reddit r/startups", "5h ago", "Software implementation risk — #1 reason enterprise deals stall"),
        ("🟠", "Hacker News", "yesterday", "PLG ceiling at $2M ARR — when to layer sales on top of product"),
        ("🔴", "Reddit r/SaaS", "2h ago", "Annual vs monthly billing — what actually moves conversion rate"),
    ],
    "ai_company": [
        ("🟠", "Hacker News", "1h ago", "AI product GTM — selling outcomes not models is the only motion"),
        ("🔴", "Reddit r/MachineLearning", "2h ago", "AI buyer fatigue is real — 80% of pilots never reach production"),
        ("🟠", "Hacker News", "3h ago", "How we went from AI demo to $1M ARR without a sales team"),
        ("🟢", "TechCrunch", "today", "AI startup funding hits $47B in Q1 2026 — application layer leads"),
        ("🔵", "Crunchbase", "today", "34 AI SaaS Series A closes this month — vertical AI dominates"),
        ("🔴", "Reddit r/startups", "4h ago", "AI pricing — per seat per output or percentage of value captured?"),
        ("🟠", "Hacker News", "yesterday", "Enterprise AI procurement added 3 new gates — legal ethics security"),
        ("🔴", "Reddit r/artificial", "2h ago", "AI hallucination liability — new blocker in regulated industry sales"),
    ],
    "data_company": [
        ("🟠", "Hacker News", "2h ago", "Data infrastructure GTM — selling to engineers vs selling to VPs"),
        ("🔴", "Reddit r/dataengineering", "3h ago", "Modern data stack consolidation — buyers picking 2 tools not 8"),
        ("🟠", "Hacker News", "5h ago", "How we sold a data platform to enterprises with no sales team"),
        ("🟢", "TechCrunch", "today", "Data tooling investment up 38% — governance and quality lead"),
        ("🔵", "Crunchbase", "today", "15 data infrastructure Series A closes — observability and quality top"),
        ("🔴", "Reddit r/datascience", "4h ago", "Data buyer is now the CDO not the CTO — GTM motion has to shift"),
        ("🟠", "Hacker News", "yesterday", "Bottom-up data tool adoption — how to convert free users to enterprise"),
        ("🔴", "Reddit r/dataengineering", "2h ago", "Data contract standards emerging — new compliance buying trigger"),
    ],
}

_KEYWORD_MAP = [
    ("fintech",        ["fintech", "payment", "banking", "lending"]),
    ("healthtech",     ["health", "medical", "clinical", "pharma", "ehr"]),
    ("legal_tech",     ["legal", "law", "contract", "regulatory"]),
    ("hr_tech",        ["hr", "human resource", "hiring", "talent", "workforce"]),
    ("edtech",         ["edtech", "education", "learning", "training", "lms"]),
    ("cybersecurity",  ["security", "cyber", "infosec", "soc", "identity"]),
    ("proptech",       ["proptech", "real estate", "property", "reit"]),
    ("insurtech",      ["insur", "insurance", "underwriting", "actuarial"]),
    ("supply_chain",   ["supply chain", "supply", "procurement", "inventory"]),
    ("marketing_tech", ["marketing", "martech", "attribution", "campaign"]),
    ("devtools",       ["devtools", "developer", "devops", "observability"]),
    ("climate_tech",   ["climate", "carbon", "esg", "sustainability"]),
    ("logistics_tech", ["logistics", "freight", "shipping", "carrier", "3pl"]),
    ("sales_tech",     ["sales", "revenue", "crm", "outbound", "pipeline", "sdr"]),
]


def get_signals(vertical: str, sub_vertical: str) -> list:
    combined = (f"{vertical or ''} {sub_vertical or ''}").lower()

    # 1. Specific vertical keyword match
    for key, keywords in _KEYWORD_MAP:
        if any(kw in combined for kw in keywords):
            return MARKET_SIGNALS[key]

    # 2. Broad software / SaaS / AI / data fallback → devtools signals
    _software_keywords = [
        "software", "saas", "platform", "application", "app",
        "workflow", "implementation", "integration", "automation",
        "api", "tool", "plugin", "extension", "ai", "ml",
        "artificial intelligence", "machine learning", "llm",
        "generative", "model", "data", "analytics", "pipeline",
        "warehouse", "lakehouse", "etl", "bi", "intelligence",
        "b2b", "enterprise", "tech",
    ]
    if any(kw in combined for kw in _software_keywords):
        return MARKET_SIGNALS["devtools"]

    # 3. Ultimate fallback
    return MARKET_SIGNALS["general"]


def run(profile: dict, client) -> dict:
    return {}
